[package]
name = "lzw-compression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
n-lzw = { path = "lib/n-lzw" }
indicatif = "0.17.7"